name: Claude Code
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]  # Removed 'closed'
  pull_request_review:
    types: [submitted]
jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude'))) ||
      (github.event_name == 'push' && github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: read
      id-token: write
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          additional_permissions: |
            actions: read
          model: "claude-opus-4-20250514"
          mcp_config: "/mcp-config.json"
          direct_prompt: |
            You are a senior iOS engineer. Focus on readability, clean code, utilizing the latest frameworks, and maintainability.
            
            When there's a push to a branch that appears to be related to an issue:
            1. Extract the issue number from the branch name if possible
            2. Check if a pull request already exists for this branch
            3. If no PR exists, create a pull request from this branch to main
            4. Include a descriptive title based on the branch name and recent commits
            5. If you can identify the issue number, use "Closes #<issue_number>" in the PR description
            6. Include a summary of the changes in the commit(s)
            
            Current branch: ${{ github.ref_name }}
            Recent commits: Check the git log for context
