name: Claude Code
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned, closed]  # Added 'closed' here
  pull_request_review:
    types: [submitted]
jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && github.event.action == 'closed' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude'))) ||
      (github.event_name == 'issues' && github.event.action != 'closed' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write  # Changed from read to write to create PRs
      issues: read
      id-token: write
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Changed from 1 to 0 to get full history for branching
      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          additional_permissions: |
            actions: read
          model: "claude-opus-4-20250514"
          mcp_config: "/mcp-config.json"
          prompt: |
            You are a senior iOS engineer. Focus on readability, clean code, utilizing the latest frameworks, and maintainability.
            
            When an issue is closed, check if there's a corresponding branch for this issue. If there is:
            1. Ensure the branch is up to date
            2. Create a pull request from the issue branch to main
            3. Include a descriptive title and body referencing the closed issue
            4. Use the format: "Closes #<issue_number>" in the PR description
